name: eShopOnWeb Build and Deploy (CLI)

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: rg-eshoponweb-patrita63
  LOCATION: eastus
  TEMPLATE-FILE: bicep-template/webapp.bicep  # ✅ Corrected path
  SUBSCRIPTION-ID: aa67cdae-2fc0-41d1-bd24-694d92814576
  WEBAPP-NAME: eshoponweb-webapp-pat25

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: Publish with dotnet
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp
          zip -r ../app.zip .

      - name: Upload .NET app artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/app.zip

      - name: Upload Bicep template artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: infra/   # Upload entire folder to preserve structure

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download .NET app artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download Bicep template artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: Verify Bicep template is present
        run: |
          echo ">>> Listing files in bicep-template/"
          ls -al bicep-template
          echo ">>> Showing content of webapp.bicep:"
          cat bicep-template/webapp.bicep

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure using Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --name webapp-deployment-${{ github.run_id }} \
              --resource-group ${{ env.RESOURCE-GROUP }} \
              --subscription ${{ env.SUBSCRIPTION-ID }} \
              --template-file ${{ env.TEMPLATE-FILE }} \
              --parameters webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }} sku=B1

      - name: Deploy .NET App to Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP-NAME }} \
              --resource-group ${{ env.RESOURCE-GROUP }} \
              --src-path .net-app/app.zip \
              --type zip \
              --output none
